area_codes = {
    "Asia": "a",
    "Afghanistan": "a-af",
    "Armenia (Republic)": "a-ai",
    "Azerbaijan": "a-aj",
    "Bahrain": "a-ba",
    "Bangladesh": "a-bg",
    "Borneo": "a-bn",
    "Burma": "a-br",
    "Bhutan": "a-bt",
    "Brunei": "a-bx",
    "Cambodia": "a-cb",
    "China": "a-cc",
    "Anhui Sheng (China)": "a-cc-an",
    "Zhejiang Sheng (China)": "a-cc-ch",
    "Chongqing (China)": "a-cc-cq",
    "Fujian Sheng (China)": "a-cc-fu",
    "Hainan Sheng (China)": "a-cc-ha",
    "Heilongjiang Sheng (China)": "a-cc-he",
    "Hubei Sheng (China)": "a-cc-hh",
    "Hong Kong (China)": "a-cc-hk",
    "Henan Sheng (China)": "a-cc-ho",
    "Hebei Sheng (China)": "a-cc-hp",
    "Hunan Sheng (China)": "a-cc-hu",
    "Inner Mongolia (China)": "a-cc-im",
    "Gansu Sheng (China)": "a-cc-ka",
    "Guangxi Zhuangzu Zizhiqu (China)": "a-cc-kc",
    "Jiangxi Sheng (China)": "a-cc-ki",
    "Guangdong Sheng (China)": "a-cc-kn",
    "Jilin Sheng (China)": "a-cc-kr",
    "Jiangsu Sheng (China)": "a-cc-ku",
    "Guizhou Sheng (China)": "a-cc-kw",
    "Liaoning Sheng (China)": "a-cc-lp",
    "Macau (China : Special Administrative Region)": "a-cc-mh",
    "Ningxia Huizu Zizhiqu (China)": "a-cc-nn",
    "Beijing (China)": "a-cc-pe",
    "Shanxi Sheng (China)": "a-cc-sh",
    "Shanghai (China)": "a-cc-sm",
    "Shandong Sheng (China)": "a-cc-sp",
    "Shaanxi Sheng (China)": "a-cc-ss",
    "Xinjiang Uygur Zizhiqu (China)": "a-cc-su",
    "Sichuan Sheng (China)": "a-cc-sz",
    "Tibet (China)": "a-cc-ti",
    "Tianjin (China)": "a-cc-tn",
    "Qinghai Sheng (China)": "a-cc-ts",
    "Yunnan Sheng (China)": "a-cc-yu",
    "Yangtze River (China)": "a-ccg",
    "Kunlun Mountains (China and India)": "a-cck",
    "Bo Hai (China)": "a-ccp",
    "Xi River (China)": "a-ccs",
    "Yellow River (China)": "a-ccy",
    "Sri Lanka": "a-ce",
    "Taiwan": "a-ch",
    "Cyprus": "a-cy",
    "Timor-Leste": "a-em",
    "Georgia (Republic)": "a-gs",
    "India": "a-ii",
    "Indonesia": "a-io",
    "Iraq": "a-iq",
    "Iran": "a-ir",
    "Israel": "a-is",
    "Japan": "a-ja",
    "Jordan": "a-jo",
    "Kyrgyzstan": "a-kg",
    "Korea (North)": "a-kn",
    "Korea (South)": "a-ko",
    "Korea": "a-kr",
    "Kuwait": "a-ku",
    "Kazakhstan": "a-kz",
    "Lebanon": "a-le",
    "Laos": "a-ls",
    "Oman": "a-mk",
    "Mongolia": "a-mp",
    "Malaysia": "a-my",
    "Nepal": "a-np",
    "New Guinea": "a-nw",
    "Philippines": "a-ph",
    "Pakistan": "a-pk",
    "Papua New Guinea": "a-pp",
    "Qatar": "a-qa",
    "Singapore": "a-si",
    "Saudi Arabia": "a-su",
    "Syria": "a-sy",
    "Tajikistan": "a-ta",
    "Thailand": "a-th",
    "Turkmenistan": "a-tk",
    "United Arab Emirates": "a-ts",
    "Turkey": "a-tu",
    "Uzbekistan": "a-uz",
    "Vietnam": "a-vt",
    "Yemen (Republic)": "a-ye",
    "Amur River (China and Russia)": "aa",
    "Bengal, Bay of": "ab",
    "Asia, Central": "ac",
    "East Asia": "ae",
    "Thailand, Gulf of": "af",
    "Mekong River": "ag",
    "Himalaya Mountains": "ah",
    "Indochina": "ai",
    "Caspian Sea": "ak",
    "Malaya": "am",
    "East China Sea": "an",
    "South China Sea": "ao",
    "Paracel Islands": "aopf",
    "Spratly Islands": "aoxp",
    "Persian Gulf": "ap",
    "Arabian Peninsula": "ar",
    "Southeast Asia": "as",
    "Tien Shan": "at",
    "Arabian Sea": "au",
    "Middle East": "aw",
    "West Bank": "awba",
    "Gaza Strip": "awgz",
    "Yellow Sea": "ay",
    "South Asia": "az",
    "Commonwealth countries": "b",
    "Intercontinental areas (Western Hemisphere)": "c",
    "Caribbean Area; Caribbean Sea": "cc",
    "Latin America": "cl",
    "Developing countries": "d",
    "Developed countries": "dd",
    "Europe": "e",
    "Albania": "e-aa",
    "Andorra": "e-an",
    "Austria": "e-au",
    "Belgium": "e-be",
    "Bosnia and Herzegovina": "e-bn",
    "Bulgaria": "e-bu",
    "Belarus": "e-bw",
    "Croatia": "e-ci",
    "Czechoslovakia": "e-cs",
    "Denmark": "e-dk",
    "Estonia": "e-er",
    "Finland": "e-fi",
    "France": "e-fr",
    "Germany (East)": "e-ge",
    "Guernsey": "e-gg",
    "Gibraltar": "e-gi",
    "Greece": "e-gr",
    "Germany (West)": "e-gw",
    "Germany": "e-gx",
    "Hungary": "e-hu",
    "Iceland": "e-ic",
    "Ireland": "e-ie",
    "Isle of Man": "e-im",
    "Italy": "e-it",
    "Jersey": "e-je",
    "Kosovo": "e-kv",
    "Liechtenstein": "e-lh",
    "Lithuania": "e-li",
    "Luxembourg": "e-lu",
    "Latvia": "e-lv",
    "Monaco": "e-mc",
    "Malta": "e-mm",
    "Montenegro": "e-mo",
    "Moldova": "e-mv",
    "Netherlands": "e-ne",
    "Norway": "e-no",
    "Poland": "e-pl",
    "Portugal": "e-po",
    "Serbia": "e-rb",
    "Romania": "e-rm",
    "Russia (Federation)": "e-ru",
    "San Marino": "e-sm",
    "Spain": "e-sp",
    "Sweden": "e-sw",
    "Switzerland": "e-sz",
    "Great Britain": "e-uk",
    "England": "e-uk-en",
    "Northern Ireland": "e-uk-ni",
    "Scotland": "e-uk-st",
    "Wales": "e-uk-wl",
    "Ukraine": "e-un",
    "Russia. Russian Empire. Soviet Union. Former Soviet Republics": "e-ur",
    "Central Chernozem Region (Russia)": "e-urc",
    "Siberia, Eastern (Russia)": "e-ure",
    "Russian Far East (Russia)": "e-urf",
    "Caucasus": "e-urk",
    "Soviet Union, Northwestern": "e-urn",
    "Volga River (Russia)": "e-urp",
    "Caucasus, Northern (Russia)": "e-urr",
    "Siberia (Russia)": "e-urs",
    "Ural Mountains (Russia)": "e-uru",
    "Siberia, Western (Russia)": "e-urw",
    "Vatican City": "e-vc",
    "North Macedonia": "e-xn",
    "Slovakia": "e-xo",
    "Czech Republic": "e-xr",
    "Slovenia": "e-xv",
    "Serbia and Montenegro; Yugoslavia": "e-yu",
    "Alps": "ea",
    "Baltic States": "eb",
    "Europe, Central": "ec",
    "Balkan Peninsula": "ed",
    "Europe, Eastern": "ee",
    "Benelux countries": "el",
    "Europe, Northern": "en",
    "Danube River": "eo",
    "Pyrenees": "ep",
    "Rhine River": "er",
    "Europe, Southern": "es",
    "Scandinavia": "ev",
    "Europe, Western": "ew",
    "Africa": "f",
    "Algeria": "f-ae",
    "Angola": "f-ao",
    "Burundi": "f-bd",
    "Botswana": "f-bs",
    "Chad": "f-cd",
    "Congo (Brazzaville)": "f-cf",
    "Congo (Democratic Republic)": "f-cg",
    "Cameroon": "f-cm",
    "Central African Republic": "f-cx",
    "Benin": "f-dm",
    "Eritrea": "f-ea",
    "Equatorial Guinea": "f-eg",
    "Ethiopia": "f-et",
    "Djibouti": "f-ft",
    "Ghana": "f-gh",
    "Gambia": "f-gm",
    "Gabon": "f-go",
    "Guinea": "f-gv",
    "Côte d'Ivoire": "f-iv",
    "Kenya": "f-ke",
    "Liberia": "f-lb",
    "Lesotho": "f-lo",
    "Libya": "f-ly",
    "Madagascar": "f-mg",
    "Mali": "f-ml",
    "Morocco": "f-mr",
    "Mauritania": "f-mu",
    "Malawi": "f-mw",
    "Mozambique": "f-mz",
    "Niger": "f-ng",
    "Nigeria": "f-nr",
    "Guinea-Bissau": "f-pg",
    "Zimbabwe": "f-rh",
    "Rwanda": "f-rw",
    "South Africa": "f-sa",
    "South Sudan": "f-sd",
    "Sao Tome and Principe": "f-sf",
    "Senegal": "f-sg",
    "Spanish North Africa": "f-sh",
    "Sudan": "f-sj",
    "Sierra Leone": "f-sl",
    "Somalia": "f-so",
    "Eswatini": "f-sq",
    "Western Sahara": "f-ss",
    "Namibia": "f-sx",
    "Togo": "f-tg",
    "Tunisia": "f-ti",
    "Tanzania": "f-tz",
    "Egypt": "f-ua",
    "Uganda": "f-ug",
    "Burkina Faso": "f-uv",
    "Zambia": "f-za",
    "Atlas Mountains": "fa",
    "Africa, Sub-Saharan": "fb",
    "Africa, Central": "fc",
    "Sahara": "fd",
    "Africa, Eastern": "fe",
    "Africa, North": "ff",
    "Congo River": "fg",
    "Africa, Northeast": "fh",
    "Niger River": "fi",
    "Nile River": "fl",
    "Sudan (Region)": "fn",
    "Africa, French-speaking Equatorial": "fq",
    "Great Rift Valley": "fr",
    "Africa, Southern": "fs",
    "Suez Canal (Egypt)": "fu",
    "Volta River (Ghana)": "fv",
    "Africa, West": "fw",
    "Zambezi River": "fz",
    "French Community": "h",
    "Indian Ocean": "i",
    "British Indian Ocean Territory": "i-bi",
    "Comoros": "i-cq",
    "Terres australes et antarctiques françaises": "i-fs",
    "Heard and McDonald Islands": "i-hm",
    "Mauritius": "i-mf",
    "Mayotte": "i-my",
    "Réunion": "i-re",
    "Seychelles": "i-se",
    "Christmas Island (Indian Ocean)": "i-xa",
    "Cocos (Keeling) Islands": "i-xb",
    "Maldives": "i-xc",
    "Atlantic Ocean": "l",
    "North Atlantic Ocean": "ln",
    "Azores": "lnaz",
    "Bermuda Islands": "lnbm",
    "Canary Islands": "lnca",
    "Cabo Verde": "lncv",
    "Faroe Islands": "lnfa",
    "Jan Mayen Island": "lnjn",
    "Madeira Islands": "lnma",
    "Svalbard (Norway)": "lnsb",
    "South Atlantic Ocean": "ls",
    "Ascension Island (Atlantic Ocean)": "lsai",
    "Bouvet Island": "lsbv",
    "Falkland Islands": "lsfk",
    "Tristan da Cunha": "lstd",
    "Saint Helena": "lsxj",
    "South Georgia and South Sandwich Islands": "lsxs",
    "Intercontinental areas (Eastern Hemisphere)": "m",
    "Arab countries": "ma",
    "Black Sea": "mb",
    "Eurasia": "me",
    "Mediterranean Region; Mediterranean Sea": "mm",
    "Red Sea": "mr",
    "North America": "n",
    "Canada": "n-cn",
    "Alberta": "n-cn-ab",
    "British Columbia": "n-cn-bc",
    "Manitoba": "n-cn-mb",
    "Newfoundland and Labrador": "n-cn-nf",
    "New Brunswick": "n-cn-nk",
    "Nova Scotia": "n-cn-ns",
    "Northwest Territories": "n-cn-nt",
    "Nunavut": "n-cn-nu",
    "Ontario": "n-cn-on",
    "Prince Edward Island": "n-cn-pi",
    "Québec (Province)": "n-cn-qu",
    "Saskatchewan": "n-cn-sn",
    "Yukon Territory": "n-cn-yk",
    "Hudson Bay": "n-cnh",
    "Maritime Provinces": "n-cnm",
    "Prairie Provinces": "n-cnp",
    "Greenland": "n-gl",
    "Mexico": "n-mx",
    "United States": "n-us",
    "Alaska": "n-us-ak",
    "Alabama": "n-us-al",
    "Arkansas": "n-us-ar",
    "Arizona": "n-us-az",
    "California": "n-us-ca",
    "Colorado": "n-us-co",
    "Connecticut": "n-us-ct",
    "Washington (D.C.)": "n-us-dc",
    "Delaware": "n-us-de",
    "Florida": "n-us-fl",
    "Georgia": "n-us-ga",
    "Hawaii": "n-us-hi",
    "Iowa": "n-us-ia",
    "Idaho": "n-us-id",
    "Illinois": "n-us-il",
    "Indiana": "n-us-in",
    "Kansas": "n-us-ks",
    "Kentucky": "n-us-ky",
    "Louisiana": "n-us-la",
    "Massachusetts": "n-us-ma",
    "Maryland": "n-us-md",
    "Maine": "n-us-me",
    "Michigan": "n-us-mi",
    "Minnesota": "n-us-mn",
    "Missouri": "n-us-mo",
    "Mississippi": "n-us-ms",
    "Montana": "n-us-mt",
    "Nebraska": "n-us-nb",
    "North Carolina": "n-us-nc",
    "North Dakota": "n-us-nd",
    "New Hampshire": "n-us-nh",
    "New Jersey": "n-us-nj",
    "New Mexico": "n-us-nm",
    "Nevada": "n-us-nv",
    "New York": "n-us-ny",
    "Ohio": "n-us-oh",
    "Oklahoma": "n-us-ok",
    "Oregon": "n-us-or",
    "Pennsylvania": "n-us-pa",
    "Rhode Island": "n-us-ri",
    "South Carolina": "n-us-sc",
    "South Dakota": "n-us-sd",
    "Tennessee": "n-us-tn",
    "Texas": "n-us-tx",
    "Utah": "n-us-ut",
    "Virginia": "n-us-va",
    "Vermont": "n-us-vt",
    "Washington (State)": "n-us-wa",
    "Wisconsin": "n-us-wi",
    "West Virginia": "n-us-wv",
    "Wyoming": "n-us-wy",
    "Appalachian Mountains": "n-usa",
    "Middle West": "n-usc",
    "Northeastern States": "n-use",
    "Middle Atlantic States": "n-usl",
    "Mississippi River": "n-usm",
    "New England": "n-usn",
    "Ohio River": "n-uso",
    "West (U.S.)": "n-usp",
    "East (U.S.)": "n-usr",
    "Missouri River": "n-uss",
    "Southwest, New": "n-ust",
    "Southern States": "n-usu",
    "Saint Pierre and Miquelon": "n-xl",
    "Central America": "nc",
    "Belize": "ncbh",
    "Costa Rica": "nccr",
    "Canal Zone": "nccz",
    "El Salvador": "nces",
    "Guatemala": "ncgt",
    "Honduras": "ncho",
    "Nicaragua": "ncnq",
    "Panama": "ncpn",
    "Great Lakes (North America); Lake States": "nl",
    "Mexico, Gulf of": "nm",
    "Great Plains": "np",
    "Rocky Mountains": "nr",
    "West Indies": "nw",
    "Antigua and Barbuda": "nwaq",
    "Aruba": "nwaw",
    "Barbados": "nwbb",
    "Bahamas": "nwbf",
    "Bonaire": "nwbn",
    "Cayman Islands": "nwcj",
    "Curaçao": "nwco",
    "Cuba": "nwcu",
    "Dominica": "nwdq",
    "Dominican Republic": "nwdr",
    "Sint Eustatius": "nweu",
    "Grenada": "nwgd",
    "Guadeloupe": "nwgp",
    "Hispaniola": "nwhi",
    "Haiti": "nwht",
    "Jamaica": "nwjm",
    "Antilles, Lesser": "nwla",
    "Leeward Islands (West Indies)": "nwli",
    "Montserrat": "nwmj",
    "Martinique": "nwmq",
    "Puerto Rico": "nwpr",
    "Saint-Barthélemy": "nwsc",
    "Saba": "nwsd",
    "Sint Maarten": "nwsn",
    "Saint-Martin": "nwst",
    "Swan Islands (Honduras)": "nwsv",
    "Turks and Caicos Islands": "nwtc",
    "Trinidad and Tobago": "nwtr",
    "United States Miscellaneous Caribbean Islands": "nwuc",
    "British Virgin Islands": "nwvb",
    "Virgin Islands of the United States": "nwvi",
    "Windward Islands (West Indies)": "nwwi",
    "Anguilla": "nwxa",
    "Saint Kitts and Nevis": "nwxi",
    "Saint Lucia": "nwxk",
    "Saint Vincent and the Grenadines": "nwxm",
    "Pacific Ocean": "p",
    "North Pacific Ocean": "pn",
    "Oceania": "po",
    "American Samoa": "poas",
    "Solomon Islands": "pobp",
    "Caroline Islands": "poci",
    "Cook Islands": "pocw",
    "Easter Island": "poea",
    "Fiji": "pofj",
    "French Polynesia": "pofp",
    "Galapagos Islands": "pogg",
    "Guam": "pogu",
    "Johnston Island": "poji",
    "Kiribati": "pokb",
    "Kermadec Islands": "poki",
    "Line Islands": "poln",
    "Melanesia": "pome",
    "Micronesia (Federated States)": "pomi",
    "New Caledonia": "ponl",
    "Vanuatu": "ponn",
    "Nauru": "ponu",
    "Pitcairn Island": "popc",
    "Palau": "popl",
    "Polynesia": "pops",
    "Samoan Islands": "posh",
    "Tokelau": "potl",
    "Tonga": "poto",
    "Micronesia": "pott",
    "Tuvalu": "potv",
    "United States Miscellaneous Pacific Islands": "poup",
    "Wallis and Futuna Islands": "powf",
    "Wake Island": "powk",
    "Samoa": "pows",
    "Mariana Islands": "poxd",
    "Marshall Islands": "poxe",
    "Midway Islands": "poxf",
    "Niue": "poxh",
    "South Pacific Ocean": "ps",
    "Cold regions": "q",
    "Arctic Ocean; Arctic regions": "r",
    "South America": "s",
    "Argentina": "s-ag",
    "Brazil": "s-bl",
    "Bolivia": "s-bo",
    "Colombia": "s-ck",
    "Chile": "s-cl",
    "Ecuador": "s-ec",
    "French Guiana": "s-fg",
    "Guyana": "s-gy",
    "Peru": "s-pe",
    "Paraguay": "s-py",
    "Suriname": "s-sr",
    "Uruguay": "s-uy",
    "Venezuela": "s-ve",
    "Amazon River": "sa",
    "Andes": "sn",
    "Rio de la Plata (Argentina and Uruguay)": "sp",
    "Antarctic Ocean; Antarctica": "t",
    "Australasia": "u",
    "Ashmore and Cartier Islands": "u-ac",
    "Australia": "u-at",
    "Australian Capital Territory": "u-at-ac",
    "Central Australia": "u-atc",
    "Eastern Australia": "u-ate",
    "Northern Australia": "u-atn",
    "New South Wales": "u-at-ne",
    "Northern Territory": "u-at-no",
    "Queensland": "u-at-qn",
    "South Australia": "u-at-sa",
    "Tasmania": "u-at-tm",
    "Victoria": "u-at-vi",
    "Western Australia": "u-at-we",
    "Coral Sea Islands": "u-cs",
    "New Zealand": "u-nz",
    "Tropics": "w",
    "Earth": "x",
    "Eastern Hemisphere": "xa",
    "Northern Hemisphere": "xb",
    "Southern Hemisphere": "xc",
    "Western Hemisphere": "xd",
    "Deep space": "zd",
    "Jupiter": "zju",
    "Mars": "zma",
    "Mercury": "zme",
    "Moon": "zmo",
    "Neptune": "zne",
    "Outer space": "zo",
    "Pluto": "zpl",
    "Solar system": "zs",
    "Saturn": "zsa",
    "Sun": "zsu",
    "Uranus": "zur",
    "Venus": "zve",
}
